### ISSUE TITLE
similar extension

### ISSUE THREAD

**Issue by vmario89** [Mr-DblH/inkscape-draw-rectangle#1]
Hi,
found your extension and lik other people making cool stuff for Inkscape. While i stumbled upon yours, i wanted to give you notice there exists some similar extension to yours: https://sourceforge.net/p/razorfoss/svn/HEAD/tree/trunk/Inkscape/InsertPaperTemplate/ 

maybe check it out also.

cheers, Mario

**Comment by Mr-DblH** [comment]
Hi Mario, thanks for the link, I have included this one in the readme.md
